#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
	type = 'prompt'
	alignment = 'left'

	[[blocks.segments]]
		type = 'os'
		style = 'diamond'
		foreground = 'p:black'
		background = 'p:white'
		leading_diamond = ''
		trailing_diamond = ''
		template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '

	[[blocks.segments]]
		type = 'path'
		style = 'diamond'
		leading_diamond = ''
		foreground = 'p:white'
		background = 'p:black'
		template = '  {{ .Path }} '

		[blocks.segments.properties]
			style = 'folder'

	[[blocks.segments]]
		type = 'git'
		style = 'powerline'
		powerline_symbol = ''
		foreground = 'p:black'
		background = 'p:deepgreen'
		background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:deepgreen{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:deepred{{ end }}', '{{ if gt .Ahead 0 }}p:deepgreen{{ end }}', '{{ if gt .Behind 0 }}p:deepred{{ end }}']
		template = ' {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Staging.Changed) (.Working.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '

		[blocks.segments.properties]
			branch_icon = ' '
			fetch_stash_count = true
			fetch_status = true
			fetch_upstream_icon = true
			fetch_worktree_count = true

	[[blocks.segments]]
		type = 'root'
		style = 'powerline'
		powerline_symbol = ''
		foreground = 'p:white'
		background = 'p:yellow'
		template = '  '

	[[blocks.segments]]
		type = 'status'
		style = 'diamond'
		foreground = 'p:white'
		background = 'p:deepblue'
		background_templates = ['{{ if gt .Code 0 }}p:deepred{{ end }}']
		leading_diamond = ''
		trailing_diamond = ''
		template = ' {{ .String }} '

		[blocks.segments.properties]
			always_enabled = true

[[blocks]]
	type = 'rprompt'
	alignment = 'right'

	[[blocks.segments]]
		type = 'shell'
		style = 'diamond'
		foreground = 'p:black'
		background = 'p:grey'
		leading_diamond = ''
		trailing_diamond = ''
		template = ' 󰞷 {{ .Name }} '

	[[blocks.segments]]
		type = 'executiontime'
		style = 'diamond'
		foreground = 'p:white'
		background = 'p:black'
		leading_diamond = ''
		trailing_diamond = ''
		template = ' 󱎫 {{ .FormattedMs }} '

		[blocks.segments.properties]
			style = 'roundrock'
			threshold = 0.0


	[[blocks.segments]]
		type = 'battery'
		style = 'diamond'
		foreground = 'p:white'
		background = 'p:deepgreen'
		leading_diamond = ''
		trailing_diamond = ''
		template = ' {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}% '

		[blocks.segments.properties]
			discharging_icon = '󰁿 '
			charging_icon = '󰂉 '
			charged_icon = '󰂅 '


	[[blocks.segments]]
		type = 'sysinfo'
		style = 'diamond'
		foreground = 'p:white'
		background = 'p:darkpink'
		leading_diamond = ''
		trailing_diamond = ''
		template = '  {{ round .PhysicalPercentUsed .Precision }} '

	[[blocks.segments]]
		type = 'time'
		style = 'diamond'
		foreground = 'p:black'
		background = 'p:white'
		leading_diamond = ''
		trailing_diamond = ''
		template = ' 󰥔 {{ .CurrentDate | date .Format }} '

[transient_prompt]
	foreground = 'p:grey'
	background = 'transparent'
	template = ' '

[secondary_prompt]
	foreground = 'p:grey'
	background = 'transparent'
	template = ' '

[palette]
	black = '#000000'
	blue = '#0000ff'
	cyan = '#00ffff'
	darkcyan = '#008888'
	darkpink = '#880088'
	darkyellow = '#888800'
	deepblue = '#000088'
	deepgreen = '#008800'
	deepred = '#880000'
	green = '#00ff00'
	grey = '#888888'
	pink = '#ff00ff'
	red = '#ff0000'
	white = '#ffffff'
	yellow = '#ffff00'
