"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 4
final_space = true

[palette]
# gruvbox dark
fg0 = '#fbf1c7'
bg1 = '#3c3836'
bg3 = '#665c54'
blue = '#458588'
aqua = '#689d6a'
green = '#98971a'
orange = '#d65d0e'
purple = '#b16286'
red = '#cc241d'
yellow = '#d79921'

[secondary_prompt]
template = " "
foreground = "p:orange"
background = "transparent"

[transient_prompt]
template = " "
foreground = "p:orange"
background = "transparent"

# ==== left prompt ====

[[blocks]]
type = "prompt"
alignment = "left"

[[blocks.segments]]
type = "os"
template = " {{.Icon}} "
foreground = "p:fg0"
background = "p:orange"
style = "diamond"
leading_diamond = ""
trailing_diamond = ""

[blocks.segments.properties]
cache_duration = "none"

[[blocks.segments]]
type = "root"
foreground = "p:fg0"
background = "p:red"
style = "diamond"
leading_diamond = ""
trailing_diamond = ""

[[blocks.segments]]
type = "path"
template = "  {{ .Path }} "
foreground = "p:fg0"
background = "p:yellow"
style = "diamond"
leading_diamond = ""
trailing_diamond = ""

[blocks.segments.properties]
cache_duration = "none"
style = "folder"

[[blocks.segments]]
type = "git"
template = " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }} "
foreground = "p:fg0"
background = "p:aqua"
background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}p:aqua{{ end }}",
  "{{ if gt .Ahead 0 }}p:blue{{ end }}",
  "{{ if gt .Behind 0 }}p:red{{ end }}",
]
style = "diamond"
leading_diamond = ""
trailing_diamond = ""

[blocks.segments.properties]
branch_icon = " "
cache_duration = "none"

# ==== right prompt ====

[[blocks]]
type = "rprompt"
alignment = "right"

[[blocks.segments]]
type = "status"
template = " {{ .String }} "
foreground = "p:fg0"
background = "p:blue"
background_templates = ["{{ if gt .Code 0 }}p:red{{ end }}"]
style = "diamond"
leading_diamond = ""
trailing_diamond = ""

[blocks.segments.properties]
always_enabled = true
cache_duration = "none"

[[blocks.segments]]
type = "executiontime"
template = " 󱎫 {{ .FormattedMs }} "
foreground = "p:fg1"
background = "p:bg3"
style = "diamond"
leading_diamond = ""
trailing_diamond = ""

[blocks.segments.properties]
cache_duration = "none"
threshold = 0.0

[[blocks.segments]]
type = "python"
template = "  {{ .Venv }} "
foreground = "p:fg0"
background = "p:aqua"
style = "diamond"
leading_diamond = ""
trailing_diamond = ""

[[blocks.segments]]
type = "battery"
template = " {{ .Icon }}{{ .Percentage }}% "
foreground = "p:fg0"
background = "p:bg1"
style = "diamond"
leading_diamond = ""
trailing_diamond = ""

[blocks.segments.properties]
discharging_icon = "󰁹 "
charging_icon = "󰂄 "
charged_icon = "󱟢 "
