# fonts
font_family family="JetBrainsMono Nerd Font"
font_size 13.0
symbol_map U+e000-U+e00a,U+ea60-U+ebeb,U+e0a0-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b7,U+e700-U+e8ef,U+ed00-U+efc1,U+f000-U+f2ff,U+f000-U+f2e0,U+f300-U+f381,U+f400-U+f533,U+f0001-U+f1af0 Symbols Nerd Font Mono
disable_ligatures cursor
cursor_trail 8
cursor_stop_blinking_after 2.0

# scrollback
scrollback_fill_enlarged_window yes

# window
remember_window_size no
initial_window_width 960
initial_window_height 600
window_padding_width 2

# tab
tab_bar_edge top
tab_bar_style slant

# colorscheme
include theme.conf
background_opacity 0.85
background_blur 8

# advanced
shell_integration enabled
notify_on_cmd_finish invisible 5.0 notify

# keyboard shortcuts
kitty_mod super
# copy & paste
map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard
# scrolling
map kitty_mod+k scroll_line_up
map kitty_mod+j scroll_line_down
map kitty_mod+shift+k scroll_page_up
map kitty_mod+shift+j scroll_page_down
# windows & tabs
map kitty_mod+enter new_window
map kitty_mod+e next_tab
map kitty_mod+t new_tab
# functional
map kitty_mod+s show_last_command_output
map super+d send_key ctrl+d
